import { Command, Option } from 'commander';

export const COMPLETION_SHELLS = ['bash', 'zsh', 'fish'] as const;
export type CompletionShell = typeof COMPLETION_SHELLS[number];

/** Returns fixed value suggestions for an option, or undefined to fall back to file/free-text completion. */
export type OptionValueProvider = (commandPath: string[], option: Option) => string[] | undefined;

interface OptionSpec {
  short?: string;
  long?: string;
  description: string;
  valueName?: string;
  variadic: boolean;
  files: boolean;
  values: string[];
}

interface CommandSpec {
  path: string[];
  description: string;
  options: OptionSpec[];
  commands: CommandSpec[];
  positionalValues: string[];
  positionalFiles: boolean;
}

const FILE_PLACEHOLDER = /path|file|dir/i;
// Only shell-safe words are emitted unquoted into generated scripts.
const SAFE_WORD = /^[\w.+/@%=,-]+$/;

function safeWords(values: Iterable<string>): string[] {
  return [...new Set(values)].filter(value => SAFE_WORD.test(value));
}

function oneLine(text: string): string {
  return text.replace(/\s+/g, ' ').trim();
}

function buildSpec(command: Command, path: string[], valueProvider?: OptionValueProvider): CommandSpec {
  const help = command.createHelp();
  const subcommands = help.visibleCommands(command);
  const siblingNames = subcommands.map(sub => sub.name()).filter(name => name !== 'help');

  const options = help.visibleOptions(command).map((option): OptionSpec => {
    const placeholder = option.flags.match(/<([^>]+)>|\[([^\]]+)\]/);
    const valueName = placeholder ? (placeholder[1] ?? placeholder[2]).replace(/\.\.\.$/, '') : undefined;
    const values = safeWords(option.argChoices ?? valueProvider?.(path, option) ?? []);
    return {
      short: option.short,
      long: option.long,
      description: oneLine(option.description),
      valueName,
      variadic: option.variadic,
      files: !!valueName && values.length === 0 && FILE_PLACEHOLDER.test(valueName),
      values,
    };
  });

  const positionalValues: string[] = [];
  let positionalFiles = false;
  for (const argument of command.registeredArguments) {
    if (argument.argChoices) positionalValues.push(...argument.argChoices);
    else if (FILE_PLACEHOLDER.test(argument.name())) positionalFiles = true;
  }

  return {
    path,
    description: oneLine(command.description()),
    options,
    positionalValues: safeWords(positionalValues),
    positionalFiles: positionalFiles || options.some(option => option.variadic && option.files),
    commands: subcommands.map(sub => {
      const spec = buildSpec(sub, [...path, sub.name()], valueProvider);
      // Commander's implicit help command takes a sibling command name.
      if (sub.name() === 'help' && sub.registeredArguments.length > 0) spec.positionalValues = siblingNames;
      return spec;
    }),
  };
}

function flatten(spec: CommandSpec): CommandSpec[] {
  return [spec, ...spec.commands.flatMap(flatten)];
}

function optionFlags(option: OptionSpec): string[] {
  return [option.short, option.long].filter((flag): flag is string => !!flag);
}

function bashScript(root: CommandSpec, programName: string): string {
  const fn = `_${programName.replace(/\W/g, '_')}_completion`;
  const all = flatten(root);
  const key = (spec: CommandSpec) => spec.path.map(part => `/${part}`).join('');

  const pathCases = all.filter(spec => spec.path.length > 0).map(key).join('|');

  const valueCases = all.flatMap(spec => spec.options.filter(option => option.valueName).map(option => {
    const patterns = optionFlags(option).map(flag => `"${key(spec)} ${flag}"`).join('|');
    const body = option.values.length > 0
      ? `COMPREPLY=($(compgen -W "${option.values.join(' ')}" -- "$cur"))`
      : ':';
    return `    ${patterns}) ${body}; return 0 ;;`;
  }));

  const wordCases = all.map(spec => {
    const commands = [...spec.commands.map(sub => sub.path[sub.path.length - 1]), ...spec.positionalValues];
    const options = spec.options.flatMap(optionFlags);
    return `    "${key(spec)}") commands="${commands.join(' ')}"; options="${options.join(' ')}" ;;`;
  });

  return `# bash completion for ${programName}
# Generated by \`${programName} completion bash\`; regenerate after upgrading.
${fn}() {
  local cur prev path word i commands="" options=""
  COMPREPLY=()
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev=""
  (( COMP_CWORD > 0 )) && prev="\${COMP_WORDS[COMP_CWORD-1]}"

  path=""
  for (( i = 1; i < COMP_CWORD; i++ )); do
    word="\${COMP_WORDS[i]}"
    case "$path/$word" in
      ${pathCases}) path="$path/$word" ;;
    esac
  done

  # Options that take a value: suggest known values, otherwise fall back to file names.
  case "$path $prev" in
${valueCases.join('\n')}
  esac

  case "$path" in
${wordCases.join('\n')}
  esac

  if [[ "$cur" == -* ]]; then
    COMPREPLY=($(compgen -W "$options" -- "$cur"))
  elif [[ -n "$commands" ]]; then
    COMPREPLY=($(compgen -W "$commands" -- "$cur"))
  fi
  return 0
}
complete -o default -F ${fn} ${programName}
`;
}

function zshQuote(text: string): string {
  return `'${text.replace(/'/g, `'\\''`)}'`;
}

function zshDescription(text: string): string {
  return text.replace(/\\/g, '\\\\').replace(/([[\]:])/g, '\\$1');
}

function zshScript(root: CommandSpec, programName: string): string {
  const base = `_${programName.replace(/\W/g, '_')}`;
  const fnName = (spec: CommandSpec) => [base, ...spec.path.map(part => part.replace(/\W/g, '_'))].join('_');

  const optionSpec = (option: OptionSpec): string => {
    let action = '';
    if (option.valueName) {
      const name = zshDescription(option.valueName);
      if (option.values.length > 0) action = `:${name}:(${option.values.join(' ')})`;
      else if (option.files) action = `:${name}:_files`;
      else action = `:${name}: `;
    }
    const tail = `[${zshDescription(option.description)}]${action}`;
    const flags = optionFlags(option);
    const repeat = option.variadic ? '*' : '';
    if (flags.length === 1) return zshQuote(repeat + flags[0] + tail);
    return `${zshQuote(`(${flags.join(' ')})${repeat}`)}{${flags.join(',')}}${zshQuote(tail)}`;
  };

  const functions = flatten(root).map(spec => {
    const specs = spec.options.map(optionSpec);
    if (spec.commands.length > 0) {
      const entries = spec.commands.map(sub =>
        zshQuote(`${sub.path[sub.path.length - 1].replace(/:/g, '\\:')}:${sub.description}`));
      const cases = spec.commands.map(sub => `        ${sub.path[sub.path.length - 1]}) ${fnName(sub)} ;;`);
      return `${fnName(spec)}() {
  local curcontext="$curcontext" state line
  local -a commands
  commands=(
${entries.map(entry => `    ${entry}`).join('\n')}
  )
  _arguments -C \\
${specs.map(item => `    ${item} \\`).join('\n')}
    '1: :->command' \\
    '*:: :->args' && return
  case $state in
    command) _describe -t commands ${zshQuote(`${[programName, ...spec.path].join(' ')} command`)} commands ;;
    args)
      case $words[1] in
${cases.join('\n')}
      esac
      ;;
  esac
}`;
    }
    const positional = spec.positionalValues.length > 0
      ? [`'1:value:(${spec.positionalValues.join(' ')})'`]
      : spec.positionalFiles ? [`'*:file:_files'`] : [];
    const lines = [...specs, ...positional];
    return `${fnName(spec)}() {
  _arguments${lines.map(item => ` \\\n    ${item}`).join('')}
}`;
  });

  return `#compdef ${programName}
# zsh completion for ${programName}
# Generated by \`${programName} completion zsh\`; regenerate after upgrading.

${functions.join('\n\n')}

if [ "$funcstack[1]" = "${base}" ]; then
  ${base} "$@"
else
  compdef ${base} ${programName}
fi
`;
}

function fishQuote(text: string): string {
  return `'${text.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function fishScript(root: CommandSpec, programName: string): string {
  const lines = [
    `# fish completion for ${programName}`,
    `# Generated by \`${programName} completion fish\`; regenerate after upgrading.`,
    `complete -c ${programName} -f`,
  ];

  const condition = (spec: CommandSpec, childNames: string[]): string => {
    if (spec.path.length === 0) return '__fish_use_subcommand';
    const parts = spec.path.map(part => `__fish_seen_subcommand_from ${part}`);
    if (childNames.length > 0) parts.push(`not __fish_seen_subcommand_from ${childNames.join(' ')}`);
    return parts.join('; and ');
  };

  for (const spec of flatten(root)) {
    const childNames = spec.commands.map(sub => sub.path[sub.path.length - 1]);
    const prefix = `complete -c ${programName} -n ${fishQuote(condition(spec, childNames))}`;

    for (const sub of spec.commands) {
      lines.push(`${prefix} -a ${sub.path[sub.path.length - 1]} -d ${fishQuote(sub.description)}`);
    }
    for (const option of spec.options) {
      const parts = [prefix];
      if (option.short) parts.push(`-s ${option.short.replace(/^-/, '')}`);
      if (option.long) parts.push(`-l ${option.long.replace(/^--/, '')}`);
      if (option.valueName) {
        if (option.values.length > 0) parts.push(`-x -a ${fishQuote(option.values.join(' '))}`);
        else if (option.files) parts.push('-r -F');
        else parts.push('-x');
      }
      parts.push(`-d ${fishQuote(option.description)}`);
      lines.push(parts.join(' '));
    }
    if (spec.positionalValues.length > 0) {
      lines.push(`${prefix} -a ${fishQuote(spec.positionalValues.join(' '))}`);
    } else if (spec.positionalFiles) {
      lines.push(`${prefix} -F`);
    }
  }

  return `${lines.join('\n')}\n`;
}

/** Generates a completion script from a Commander program, so completions always match the registered commands. */
export function generateCompletionScript(
  shell: CompletionShell,
  program: Command,
  valueProvider?: OptionValueProvider
): string {
  const root = buildSpec(program, [], valueProvider);
  const name = program.name();
  if (!SAFE_WORD.test(name) || name.includes('/')) throw new Error(`Unsupported program name for completions: ${name}`);
  switch (shell) {
    case 'bash': return bashScript(root, name);
    case 'zsh': return zshScript(root, name);
    case 'fish': return fishScript(root, name);
    default: throw new Error(`Unsupported shell: ${shell as string}`);
  }
}
